---

- hosts: all
  become: true
  tasks:
  
  - name: install apache and php
    tags: apache, centos
    package:
      name: 
        - "{{ apache_package }}"
        - "{{  php_package }}"
      state: latest
      update_cache: yes
